apiVersion: v1
kind: Service
metadata:
  name: edge-service
  labels:
    {{- include "mel-platform.edgeServiceLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.edgeService.port }}
      targetPort: {{ .Values.edgeService.port }}
      nodePort: 30080
      protocol: TCP
  selector:
    app: edge-service